name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Optimize images
        run: node scripts/optimize-logo.js

      - name: Validate servers.json
        run: node scripts/validate-servers.js

      - name: Build
        env:
          # Set via GitHub repository Variables or Secrets
          # Example value: https://<your-pages-project>.pages.dev/api
          REACT_APP_PROXY_URL: ${{ vars.REACT_APP_PROXY_URL || secrets.REACT_APP_PROXY_URL }}
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          # Set to true if you want a single-commit history on gh-pages
          # force_orphan: true
